name: Build and Release mikasa flasher

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Nuitka
      run: pip install nuitka
    - name: Build executable
      run: python -m nuitka --onefile --follow-imports --assume-yes-for-downloads test.py
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: mikasa.dist/mikasa.exe
        name: Release ${{ github.ref_name }}
        body: "Automated release for ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
